### PR TITLE
fix(config): Make css extract more flexible

### LINKED ISSUE #291: Webpack HMR plugin conflict
I have a custom loader for my application that is something like this:

```
{
  test: /custom.js$/,
  exclude: /node_modules/,
  loader: paths.client('lib/bundler'),
}
```

This conflicts with the HMR loader in `_development.js` because it checks for `/js/` in `loaders.test` then adds to this array `loader.query.env.development.plugins[0][1].transforms`. This conditional looks to be babel specific so instead of the regex test, what about just testing for the loader `if (loader.loader === 'babel')`?

### PR DESCRIPTION
**Pull request by patrickheeney**
To fix #291

### CODE REVIEW

File: build/webpack/_production.js [hunk 1]
```diff
@@ -16,17 +16,37 @@ export default (webpackConfig) => {
...
+  let appliedExtractCSS = false
   webpackConfig.module.loaders = webpackConfig.module.loaders.map(loader => {
-    if (/css/.test(loader.test)) {
-      const [first, ...rest] = loader.loaders
+    if (!loader.loaders) {
+      return loader
+    }
+
+    let hasCSSLoader = false
+    loader.loaders.forEach(styleLoader => {
```
Comment (davezuko) [inline build/webpack/_production.js]: Hey, this could probably be a bit short (while also removing the initial `loader.loaders` check at the top):

```js
if (
  !loader.loaders ||
  loader.loaders.reduce((hasLoader, loader) => {
    return hasLoader || /css/.test(loader.split('?')[0])
  }, false)
) {
  return
}
```

Thoughts?

Comment (davezuko) [inline build/webpack/_production.js]: /cc @justingreenberg

Comment (patrickheeney) [inline build/webpack/_production.js]: I personally am not fond of the inline function in the if statement, but if thats what you want? This could produce false positives with any loader with css in the name like `postcss` right?

Comment (davezuko) [inline build/webpack/_production.js]: Good point, but what you ever use `postcss` without `css-loader`? I only mention the `css` shorthand since I was actually planning on removing the `-loader` suffixes.

And as far as the inline function, I'm just trying to condense the logic to keep the configuration a bit smaller. Honestly not that big of a deal. I think it's nice to avoid flag variables as much as possible, so this was following along those lines.

Comment (justingreenberg) [inline build/webpack/_production.js]: you could add anchor operators to the regex ie `/^css$/.test(loader.split('?')[0])`

> I only mention the css shorthand since I was actually planning on removing the -loader suffixes.
:+1: the `-loader` is unnecessary

**Comment by patrickheeney** [comment]
@davezuko @justingreenberg PR updated.

**Comment by davezuko** [comment]
I like this a lot more, thank you ^^. I'll pull it down and rebase when I get a chance.
