### PR TITLE
fix(config): Make babel plugin overrides more flexible

### LINKED ISSUE #291: Webpack HMR plugin conflict
I have a custom loader for my application that is something like this:

```
{
  test: /custom.js$/,
  exclude: /node_modules/,
  loader: paths.client('lib/bundler'),
}
```

This conflicts with the HMR loader in `_development.js` because it checks for `/js/` in `loaders.test` then adds to this array `loader.query.env.development.plugins[0][1].transforms`. This conditional looks to be babel specific so instead of the regex test, what about just testing for the loader `if (loader.loader === 'babel')`?

### PR DESCRIPTION
**Pull request by patrickheeney**
To fix #291

### CODE REVIEW

File: build/webpack/_development.js [hunk 1]
```diff
@@ -41,12 +42,33 @@ export default (webpackConfig) => {
           imports   : ['react'],
           locals    : ['module']
         }
-        loader.query.env.development.plugins[0][1].transforms
-          .push(reactTransformHmr)
+
+        loader.query.env.development.plugins =
+          loader.query.env.development.plugins.map(plugin => {
```
Comment (justingreenberg) [inline build/webpack/_development.js]: i mean, i know it's an ugly mutation but this really seems like overkill

Comment (patrickheeney) [inline build/webpack/_development.js]: Overkill in what way?

Comment (patrickheeney) [inline build/webpack/_development.js]: If you are referring to the verbosity of it all, I don't see a way to be flexible and succinct. It is a starter-kit so the order of the plugins is going to change ads more are added or removed.

Comment (justingreenberg) [inline build/webpack/_development.js]: i'm sorry i wrote that really quickly didn't mean for it to come off like that!

yea i just meant it's a verbose solution for something that was one line. i hate that the mutation is hard-coded the way that it is, but it's so easy to understand the former way, and so complicated the latter. 

i totally understand on flexibility, but i think simplicity trumps in this instance. i'll leave it up to @davezuko  

if we leave it hard-coded, i agree we should make it a convention that react-transform must the first plugin and add a comment in _base webpack config

File: build/webpack/_development.js [hunk 2]
```diff
@@ -32,8 +32,9 @@ export default (webpackConfig) => {
     // but _only_ when HMR is enabled. Putting this in the default development
     // configuration will break other tasks such as test:unit because Webpack
     // HMR is not enabled there, and these transforms require it.
+    let appliedHmr = false
     webpackConfig.module.loaders = webpackConfig.module.loaders.map(loader => {
-      if (/js(?!on)/.test(loader.test)) {
+      if (loader.loader === 'babel') {
```
Comment (davezuko) [inline build/webpack/_development.js]: I'd prefer we just update this loader test and keep the rest of the original logic for the time being. @justingreenberg @patrickheeney thoughts? I know it could cause some issues with extensibility, but we can't cleanly accommodate every use case while remaining declarative.

File: build/webpack/_development.js (hunk 1 above)
Comment (justingreenberg) [inline build/webpack/_development.js]: @patrickheeney either way, this is a very elegant solution... the new plugin syntax is insane!

File: build/webpack/_development.js (hunk 2 above)
Comment (justingreenberg) [inline build/webpack/_development.js]: :+1:

File: build/webpack/_development.js (hunk 1 above)
Comment (davezuko) [inline build/webpack/_development.js]: @justingreenberg definitely agree ^^, I hate the syntax, it makes configuration horrendously complicated.

File: build/webpack/_development.js (hunk 2 above)
Comment (patrickheeney) [inline build/webpack/_development.js]: Since its a simple change, feel free to adjust on your next commit. I will close this PR.

**Comment by patrickheeney** [comment]
@davezuko @justingreenberg PR updated. Is this acceptable?

**Comment by davezuko** [comment]
Much easier to read, thank you.

File: build/webpack/_development.js [hunk 3]
```diff
@@ -33,14 +33,20 @@ export default (webpackConfig) => {
     // configuration will break other tasks such as test:unit because Webpack
     // HMR is not enabled there, and these transforms require it.
     webpackConfig.module.loaders = webpackConfig.module.loaders.map(loader => {
-      if (/js(?!on)/.test(loader.test)) {
+      if (loader.loader === 'babel') {
         debug('Apply react-transform-hmr to babel development transforms')
 
+        if (!loader.query.env.development.plugins[0][0] !== 'react-transform') {
```
Comment (justingreenberg) [inline build/webpack/_development.js]: much better than a comment in `_base.js` :+1: thank you!
